### ISSUE TITLE
win下载安装包运行后，流程设计页面报错：流程定义内容解析失败。而且不能新建流程

### ISSUE THREAD

**Issue by Luffy0317** [somta/Juggle#1]
### 基础信息
操作系统：win11 
Juggle版本:0.6.0
部署方式：安装包

### 问题描述
win下载安装包运行后，流程设计页面报错：流程定义内容解析失败。而且不能新建流程

### 错误日志或截图
![image](https://github.com/somta/Juggle/assets/49771391/ad47a9f7-fcc1-42f6-8cbc-8428f63551b3)

**Comment by somta** [comment]
0.6.0-BETA版本还只是一个测试版本，第一个基础可用的release版本会在近期发布，同时添加了一些新的能力，可以持续关注一下，同时欢迎提一下你的需求，帮助我们做个这个项目！

**Comment by xljqq** [comment]
我也在关注这个项目，想请问下，目前支不支持变量参数的传递，存在上一节点的参数传递到下一节点或者后续节点的这种流程编排方式。

**Comment by somta** [comment]
> 我还在关注这个项目，想提问下，目前支不支持变量参数的传递，存在上一个节点的参数传递到下一个节点或者后续节点的这种流程编排方式。

跨节点的变量传递是流程编排的基础能力，肯定是支持的，且在第一个基础版本我们就会支持该能力！

**Comment by somta** [comment]
> 我还在关注这个项目，想提问下，目前支不支持变量参数的传递，存在上一个节点的参数传递到下一个节点或者后续节点的这种流程编排方式。

跨节点的变量传递是流程编排的基础能力，肯定是支持的，且在第一个基础版本我们就会支持该能力！

**Comment by xljqq** [comment]
好的，非常期待

**Comment by 1584898862** [comment]
你好，请问第一个基础可用的版本发布了吗

**Comment by somta** [comment]
> 你好，请问第一个基础可用的版本发布了吗

经过多个夜晚的奋斗，第一个版本已于今日发布，欢迎使用和提意见
