### ISSUE TITLE
希望支持从例如list[n].billCode取值

### ISSUE THREAD

**Issue by Bukuchengkuyuan** [somta/Juggle#11]
### 希望支持从例如list[n].billCode取值
例如用jsonpath解析数据

**Comment by somta** [comment]
> ### 希望支持从例如list[n].billCode取值
> 例如用jsonpath解析数据

这个能力后在后面的变量表达式中支持，目前要取列表中一个对象的某个值，建议直接使用Groovy脚本取值，然后赋值给一个对象
