### ISSUE TITLE
新增jsonpath提取参数值，望采纳

### ISSUE THREAD

**Issue by xljqq** [somta/Juggle#12]
您好，代码新增了jsonpath支持，支持任务执行前从入参中使用jsonpath规则提取参数值到中间变量，在节点任务执行后，从出参中使用jsonpath提取结果出差到目标出参中。由于代码无法直接提交，目前代码在https://gitee.com/xljqq/Juggle的develop-jsonpath分支，望采纳，谢谢

**Comment by somta** [comment]
> 您好，代码新增了jsonpath支持，支持任务执行前从入参中使用jsonpath规则提取参数值到中间变量，在节点任务执行后，从出参中使用jsonpath提取结果出差到目标出参中。由于代码无法直接提交，目前代码在[https://gitee.com/xljqq/Juggle的develop-jsonpath分支，望采纳，谢谢](https://gitee.com/xljqq/Juggle%E7%9A%84develop-jsonpath%E5%88%86%E6%94%AF%EF%BC%8C%E6%9C%9B%E9%87%87%E7%BA%B3%EF%BC%8C%E8%B0%A2%E8%B0%A2)

非常感谢对Juggle的支持，这个建议非常好，但是操作上有点过于技术化了，后续我们可以考虑使用变量表达式来实现对变量的操作

**Comment by xljqq** [comment]
是的，确实需要一定的技术，有更好的表达方式就更好了。
