### ISSUE TITLE
Groovy相关

### ISSUE THREAD

**Issue by strife-cross** [somta/Juggle#13]
1、建议引入org.codehaus.groovy替换apache的groovy，因为org.codehaus.groovy功能更全，比如JSON的功能
```xml
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-all</artifactId>
    <version>2.4.21</version>
</dependency>
```

2、是否考虑使用Java原生的ScriptEngine来执行Groovy代码，这样效率会更高

**Comment by somta** [comment]
> 1、建议引入org.codehaus.groovy替换apache的groovy，因为org.codehaus.groovy功能更全，比如JSON的功能
> 
> ```
> <dependency>
>     <groupId>org.codehaus.groovy</groupId>
>     <artifactId>groovy-all</artifactId>
>     <version>2.4.21</version>
> </dependency>
> ```
> 
> 2、是否考虑使用Java原生的ScriptEngine来执行Groovy代码，这样效率会更高

经过调研后还是决定使用apache的groovy，原因是org.codehaus.groovy已经都迁移到apache的groovy包，从4.x开始只会维护apache的groovy包；考虑到最小化的原则，之前是没有引入json的包，在最新的1.2.0版本引入了groovy的包，具体使用可以参考 https://www.juggle.plus/docs/guide/user/nodes/code-node

没有使用java原生的引擎，因为需要注入一些变量到执行引擎内部，且Groovy中的执行引擎对groovy的执行更加友好
