### ISSUE TITLE
中间变量保存问题

### ISSUE THREAD

**Issue by yy1193889747** [somta/Juggle#15]
### 基础信息
操作系统：macOs
Juggle版本：develop分支

### 问题描述
中间参数选自定义对象类型保存不了，应该是前端问题，直接写库是可以

### 错误日志或截图
<img width="1530" alt="image" src="https://github.com/somta/Juggle/assets/20589920/5460aa9d-9886-471a-a1f1-ea4150adee3a">

**Comment by somta** [comment]
> ### 基础信息
> 操作系统：macOs Juggle版本：develop分支
> 
> ### 问题描述
> 中间参数选自定义对象类型保存不了，应该是前端问题，直接写库是可以
> 
> ### 错误日志或截图
> <img alt="image" width="1530" src="https://private-user-images.githubusercontent.com/20589920/347808788-5460aa9d-9886-471a-a1f1-ea4150adee3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTEyNjYsIm5iZiI6MTcyMTAxMDk2NiwicGF0aCI6Ii8yMDU4OTkyMC8zNDc4MDg3ODgtNTQ2MGFhOWQtOTg4Ni00NzFhLWExZjEtZWE0MTUwYWRlZTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDAyMzYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNDM1ZjZlZTMzMDU3ZmIyYjQ1NzdiNmNkODZkODIwOGU3MzExNDU2OTVmMTBlOGNmNjAzNTU5YTEyMDlkNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9l_xSZQEIGQkiA5WFA731NducE-179oa0mw_cjw-T5s">

周末已经将该问题，这个问题是由于最近新迭代的功能导致的，该功能还为经过完整的测试，develop分支也是一个开发分支，体验和阅读源码还是建议使用master分支
