### ISSUE TITLE
MethodNodeExecutor不支持https协议

### ISSUE THREAD

**Issue by tankqian** [somta/Juggle#16]
MethodNodeExecutor不支持https协议，会报错

**Comment by somta** [comment]
https是支持的，具体报什么错误呢？

**Comment by tankqian** [comment]
![image](https://github.com/user-attachments/assets/9fcce7ee-9b9e-41fe-b033-477cd9b77deb)

问题出现在入参和出参的序列化和反序列化，如图，用JsonSerializeHelper.serialize总是报错【HTTP/1.1 504 Gateway Time-out】，用hutool的JSONUtil.toJsonStr就不报错了

**Comment by tankqian** [comment]
![image](https://github.com/user-attachments/assets/9fcce7ee-9b9e-41fe-b033-477cd9b77deb)

问题出现在入参和出参的序列化和反序列化，如图，用JsonSerializeHelper.serialize总是报错【HTTP/1.1 504 Gateway Time-out】，用hutool的JSONUtil.toJsonStr就不报错了

**Comment by somta** [comment]
方便提供一下接口例子和错误信息么，我排查一下

**Comment by somta** [comment]
该问题已经在Juggle v1.2.1版本修复
