### ISSUE TITLE
下载代码后，启动，网页打不开

### ISSUE THREAD

**Issue by juin33** [somta/Juggle#18]
![image](https://github.com/user-attachments/assets/e94144b8-fd78-4c45-90c6-5b1dfa2ff37e)

**Comment by somta** [comment]
> ![image](https://private-user-images.githubusercontent.com/24289671/351636080-e94144b8-fd78-4c45-90c6-5b1dfa2ff37e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTY3NzUsIm5iZiI6MTcyMTg5NjQ3NSwicGF0aCI6Ii8yNDI4OTY3MS8zNTE2MzYwODAtZTk0MTQ0YjgtZmQ3OC00YzQ1LTkwYzYtNWIxZGZhMmZmMzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA4MzQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NTQxYTlmNzQ3MjY1NzZhN2RiZmE0M2UyMWRmNzcxYmQwODc1MDFkMTgxMGZlMzZiZGZkOTQ5YTEwMWJhZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E9i03e_18meKwVpZsOOHOvyRC3xy9DHFqmd6Oh-QHBE)

如果是体验的化建议直接下载对应的安装包，一键运行即可跑起来；如果是想学习源码的话，应该juggle采用的是前后端分离的架构，你还需要启动console-ui这个vue项目，并指向console这个SpringBoot项目才能调试哦
