### ISSUE TITLE
返回值没有对不需要的字段进行过滤

### ISSUE THREAD

**Issue by 1584898862** [somta/Juggle#2]
没有对不需要的字段进行过滤。
定义的返回参数对象有四个属性，返回值却高于四个。
![mmexport1711168538932](https://github.com/somta/Juggle/assets/75118629/49a2bf08-de2b-45b8-983a-912bf56e8f83)
![mmexport1711168542515](https://github.com/somta/Juggle/assets/75118629/f7611d08-b407-49f2-be1d-4ecb385dab3a)
![mmexport1711168611667](https://github.com/somta/Juggle/assets/75118629/1ff16037-2b64-4cb8-8dd9-f62cf9e94679)

**Comment by somta** [comment]
> 没有对不需要的字段进行过滤。 定义的返回参数对象有四个属性，返回值却高于四个。 ![mmexport1711168538932](https://private-user-images.githubusercontent.com/75118629/316217222-49a2bf08-de2b-45b8-983a-912bf56e8f83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNzEyMzIsIm5iZiI6MTcxMTE3MDkzMiwicGF0aCI6Ii83NTExODYyOS8zMTYyMTcyMjItNDlhMmJmMDgtZGUyYi00NWI4LTk4M2EtOTEyYmY1NmU4ZjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDA1MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNWU2ZDMyZDQ3ZjFiMWM1YjRmZTBmZmZmYzY0OTRjZjI5MmU5NTUwM2JlNDg4ZWMwMTZjMTJhZmJmNWExYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DVdjae8n82TMVZolCiKeMRl1Xf3lrfemoSf-uUVQfug) ![mmexport1711168542515](https://private-user-images.githubusercontent.com/75118629/316217227-f7611d08-b407-49f2-be1d-4ecb385dab3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNzEyMzIsIm5iZiI6MTcxMTE3MDkzMiwicGF0aCI6Ii83NTExODYyOS8zMTYyMTcyMjctZjc2MTFkMDgtYjQwNy00OWYyLWJlMWQtNGVjYjM4NWRhYjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDA1MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMDE2MDJkODZmNDZjOGU0MjVkMzU5MmUwOWYyNGE0MGM5OTY4NzY5NGNkMzRlZGRlNDQxZjBlM2I4ZDRmMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PCStnFOCTEBdM7qDHLNYj3FEwS215A9Aq0ZPE-7DXL8) ![mmexport1711168611667](https://private-user-images.githubusercontent.com/75118629/316217268-1ff16037-2b64-4cb8-8dd9-f62cf9e94679.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNzEyMzIsIm5iZiI6MTcxMTE3MDkzMiwicGF0aCI6Ii83NTExODYyOS8zMTYyMTcyNjgtMWZmMTYwMzctMmI2NC00Y2I4LThkZDktZjYyY2Y5ZTk0Njc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDA1MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmZDJkZGJhMjhlYzA2MDZkMWJhM2M4YTQ2MDcxNDdkMTdiODIwN2ZlNmVmM2Y3ODNmMzcxODIwODgyNWYzMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fwd7Tc0AEs0aonQHAaTyGiTCpzL4hFrIEi0Npv07nfU)

这应该是一个漏测的bug，下个版本修复掉

**Comment by somta** [comment]
考虑到后期会做原始响应数据提取，因此不打算将值进行额外处理
