### ISSUE TITLE
docker启动问题

### ISSUE THREAD

**Issue by AsherAla** [somta/Juggle#24]
### 基础信息
操作系统：linux        如：cenos
Juggle版本：1.2.1   如：1.2.1
部署方式：Docker         如：Docker

### 问题描述
docker启动成功 但是无法登录

### 复现步骤
1.docker build -t juggle .
2. docker run --name juggle -d -p 9127:9127 juggle:latest
3.

### 错误日志或截图
![9f9e2a1aa5fae50a8bd669257c0b4a00](https://github.com/user-attachments/assets/0a206a65-f520-4eb4-a8e5-a94ca9a2bcf7)
![image](https://github.com/user-attachments/assets/051c0fb9-31c0-47d7-8da1-79e7cf55a843)
![d28f49a05b6cf5c0a3c9ee80b6497743](https://github.com/user-attachments/assets/0194a8c5-0803-47c5-91f6-db1ea2c4897d)

**Comment by AsherAla** [comment]
DockerFile内容：
`FROM openjdk:8

# 自己创建的工作目录
ENV workdir=/usr/local/juggle/
COPY . ${workdir}
WORKDIR ${workdir}
EXPOSE 9127
CMD ["java","-jar","juggle-server.jar"]
`

**Comment by AsherAla** [comment]
dockerfile内容：
`
FROM openjdk:8

ENV workdir=/usr/local/juggle/
COPY . ${workdir}
WORKDIR ${workdir}
EXPOSE 9127
CMD ["java","-jar","juggle-server.jar"]

`

**Comment by somta** [comment]
我们已经定位到问题了，是之前juggle:v1.2.1版本忘记将H2数据库的元数据打入到镜像导致的，可以先使用mysql作为数据源使用Juggle，具体可以参考
在config文件夹中新增一个配置文件，如下
`server.port=9127
spring.application.name=juggle

##H2##
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:file:/data/db_juggle;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;IGNORECASE=TRUE;AUTO_SERVER=TRUE;OLD_INFORMATION_SCHEMA=TRUE
#spring.datasource.username=sa
#spring.datasource.password=juggle
#spring.h2.console.enabled=true
#spring.h2.console.settings.web-allow-others=true
#spring.h2.console.path=/h2-console

##MySql##
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/juggle?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456

##Redis Cache##
#juggle.cache.cache-type="redis"
#juggle.cache.redis.model="single"
#juggle.cache.redis.address=127.0.0.1:6379
#juggle.cache.redis.password=`

启动文件如下：
version: '3'
services:
  juggle:
    image: somta/juggle:v65
    container_name: juggle
    ports:
      - "9127:9127"
    volumes:
      - ./conf/application.properties:/home/juggle/conf/application.properties


另外为了解决访问不了外网的问题，我将juggle的进行推送了一份到阿里云的镜像仓库，地址为：
registry.cn-heyuan.aliyuncs.com/somta/juggle:v1.2.1

**Comment by somta** [comment]
已经在Juggle v1.2.2版本修复该问题
