### ISSUE TITLE
接口调用日志记录功能

### ISSUE THREAD

**Issue by zhenghua0102** [somta/Juggle#25]
### 基础信息
想在MethodNodeExecutor.doExecute方法中加日志记录，但是这个方法又在core中 无法调用数据库，请问有啥好方案么？

### 复现步骤
1.
2.
3.

**Comment by somta** [comment]
这边是想将哪些信息记录到数据库呢？

**Comment by zhenghua0102** [comment]
将接口的请求参数和返回参数记录到数据库

**Comment by somta** [comment]
> 将接口的请求参数和返回参数记录到数据库

我有规划实现这个功能，但是会在后面一点，如果你要优雅的实现，如果你想优雅的实现，可以用Spring事件将相关数据抛出去

**Comment by zhenghua0102** [comment]
好的 谢谢
