### ISSUE TITLE
建议增加格式转换组件

### ISSUE THREAD

**Issue by 1584898862** [somta/Juggle#3]
数据类型完全一致才能映射成功。
建议增加格式转换组件。通过配置一定的转换规则
类似于java stream api，允许将某个字段数据通过格式转换后转换为另一种格式的数据。
![mmexport1711168850522](https://github.com/somta/Juggle/assets/75118629/5ddbbdf5-bbc9-4630-b09d-93bc97326651)

**Comment by somta** [comment]
> 数据类型完全一致才能映射成功。 建议增加格式转换组件。通过配置一定的转换规则 类似于java stream api，允许将某个字段数据通过格式转换后转换为另一种格式的数据。 ![mmexport1711168850522](https://private-user-images.githubusercontent.com/75118629/316217516-5ddbbdf5-bbc9-4630-b09d-93bc97326651.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNzExMTksIm5iZiI6MTcxMTE3MDgxOSwicGF0aCI6Ii83NTExODYyOS8zMTYyMTc1MTYtNWRkYmJkZjUtYmJjOS00NjMwLWIwOWQtOTNiYzk3MzI2NjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDA1MTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZTJiMmI5YTIzODYyODE3NDI4NWVhNDY5YmMxODZkZDU3YzkxNWNlNTc0ZWU0OGIxYmEzY2JiNjdiYTMyMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QkQmFFHcUDW0A9jXTM2z4VHAKZz_Wg74tc2af6iy8lY)

这个功能是有规划的，第一个版本是由于时间原因还没没上，后续版本会补上来

**Comment by somta** [comment]
> 数据类型完全一致才能映射成功。 建议增加格式转换组件。通过配置一定的转换规则 类似于java stream api，允许将某个字段数据通过格式转换后转换为另一种格式的数据。 ![mmexport1711168850522](https://private-user-images.githubusercontent.com/75118629/316217516-5ddbbdf5-bbc9-4630-b09d-93bc97326651.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzI4MTgsIm5iZiI6MTcxMjQ3MjUxOCwicGF0aCI6Ii83NTExODYyOS8zMTYyMTc1MTYtNWRkYmJkZjUtYmJjOS00NjMwLWIwOWQtOTNiYzk3MzI2NjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA2NDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MzVhM2M5NDkyN2JlYWViNzExZTg2OWQzNGM0NTUyMTVlZDFkZTI4YTQ2MTYyYjU5MjE4ZGNiNTdiZTBlODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oVdzvHxZtKCyWgi-gMrCf9_Bt7aClQi-95WwJmuIJME)

我们对Juggle的定位并不一定只能使用java语言，因此我们允许在流程中使用自定义代码进行数据类型转换，且在1.1.0版本已经上线自定义代码节点来满足该需求
