### ISSUE TITLE
发布的API传参问题

### ISSUE THREAD

**Issue by darrenzhou2017666** [somta/Juggle#30]
### 问题描述
对外发布的API是Get方式，因而传参的时候，如果遇到有嵌套的对象，如
```
@Data
public class DataDto{
    public int id;
    public String name;
}
@Data
public class NodeDto{
    public int id;
    public String name;
    public DataDto data;
}
```
,当输入参数是NodeDto类型时候，没法正确传参。

**Comment by somta** [comment]
> ### 问题描述
> 对外发布的API是Get方式，因而传参的时候，如果遇到有嵌套的对象，如
> 
> ```
> @Data
> public class DataDto{
>     public int id;
>     public String name;
> }
> @Data
> public class NodeDto{
>     public int id;
>     public String name;
>     public DataDto data;
> }
> ```
> 
> ,当输入参数是NodeDto类型时候，没法正确传参。

流程入参是对象的问题，我们将在juggle 1.2.3版本修复
