### ISSUE TITLE
页面显示有误

### ISSUE THREAD

**Issue by darrenzhou2017666** [somta/Juggle#38]
### 问题描述

1.新增一个传入参数为复合对象的接口：
如：
```
@Data
public class ClassA{
    private Integer nodeId;
    private ClassB  testData;
}
```
2.定义一个流程，将这个接口作为一个方法节点
3.页面选择入参“赋值”时候，选择后对应的下拉框还是空的（其实已经生效的，只是没显示出来）。

**Comment by somta** [comment]
这个是填写参数时，未指定参数名称导致，并不是系统bug
