### ISSUE TITLE
建议增加 IDEA Plugin 插件，预览以及编辑流程

### ISSUE THREAD

**Issue by xingguang2013** [somta/Juggle#4]
### 基础信息
操作系统：Windows 11 23H2
Juggle版本：1.0.0
部署方式：Docker

### 问题描述
建议增加 IDEA Plugin 插件，预览以及编辑流程，在 IDEA 中进行流程可视化以及编辑

**Comment by somta** [comment]
> ### 基础信息
> 操作系统：Windows 11 23H2 Juggle版本：1.0.0 部署方式：Docker
> 
> ### 问题描述
> 建议增加 IDEA Plugin 插件，预览以及编辑流程，在 IDEA 中进行流程可视化以及编辑

Juggle本身已经提供了可视化的编辑流程，后续可能会考虑提供IDEA的插件，但是这是相对后期的功能，目前还有非常多功能需要等待开发
