### ISSUE TITLE
新增中间变量后，未保存流程的情况下，无法调整变量的类型，确定不生效

### ISSUE THREAD

**Issue by 654894017** [somta/Juggle#40]
### 基础信息
操作系统：xxx         如：Ubuntu
Juggle版本：x.x.x    如：1.0.0
部署方式：xxx         如：Docker

### 问题描述
新增中间变量后，未保存流程的情况下，无法调整变量的类型，确定不生效

### 复现步骤
1.
![image](https://github.com/user-attachments/assets/34d5be75-25d3-4bca-bd80-6421894120ae)

2.
3.

**Comment by somta** [comment]
> ### 基础信息
> 操作系统：xxx 如：Ubuntu Juggle版本：x.x.x 如：1.0.0 部署方式：xxx 如：Docker
> 
> ### 问题描述
> 新增中间变量后，未保存流程的情况下，无法调整变量的类型，确定不生效
> 
> ### 复现步骤
> 
> ![image](https://private-user-images.githubusercontent.com/18103375/397998538-34d5be75-25d3-4bca-bd80-6421894120ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NzM4OTcsIm5iZiI6MTczNDk3MzU5NywicGF0aCI6Ii8xODEwMzM3NS8zOTc5OTg1MzgtMzRkNWJlNzUtMjVkMy00YmNhLWJkODAtNjQyMTg5NDEyMGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE3MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMDkwMzJmMmNhNzEwMDk0MmY5M2Q0NTQxMWExZWJiODFmYjdhYjhiZjY2NWVmYjU5MzNlNWVmYmMxZjU3NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nGJMPLsEz3dzr9j-DQJiyUd-ywZWWPCoEmGyvbPa7cM)
> 
> 
> ### 错误日志或截图

问题已定位并修复，将在下个版本更新上线
