### ISSUE TITLE
建议增加循环结构、jar包sdk报文加解密、希望支持从例如list[n].billCode取值

### ISSUE THREAD

**Issue by Bukuchengkuyuan** [somta/Juggle#6]
# 建议增加循环结构

# jar包sdk报文加解密

# 希望支持从例如list[n].billCode取值
> 例如用jsonpass语法 ，并且希望支持js脚本处理中间变量

**Comment by somta** [comment]
> # 建议增加循环结构
> # jar包sdk报文加解密
> # 希望支持从例如list[n].billCode取值
> > 例如用jsonpass语法 ，并且希望支持js脚本处理中间变量

麻烦将多个功能拆分成多个issue，方便后续根据和关闭，谢谢
